default: &DEFAULT
  num_epochs: 1000
  batch_size: 256
  audio_processed_path: "data.json"

preprocess:
  <<: *DEFAULT
  audio_dir: "data/genres_original"
  image_dir: "data/images_original"
  sample_rate: 22050
  n_fft: 2048
  n_mfcc: 13
  hop_length: 512
  track_duration: 30
  num_segments: 10
  ignored_audio: "data/genres_original/jazz/jazz.00054.wav"



MLP:
  <<: *DEFAULT
  model_name: mlp
  data_dir: "fashionmnist" # https://www.kaggle.com/zalando-research/fashionmnist
  checkpoint_dir: "checkpoints/mlp"
  log_dir: 'logs/mlp'
  dataset_class: "FashionMNISTDataset"
  flatten: True
  gpu_vis_dev: '0'
  num_epochs: 10
  batch_size: 256
  lr: 0.0001

CNN:
  <<: *DEFAULT
  model_name: cnn
  data_dir: "fashionmnist"
  checkpoint_dir: "checkpoints/cnn"
  log_dir: 'logs/cnn'
  dataset_class: "FashionMNISTDataset"
  flatten: False
  gpu_vis_dev: '0'
  num_epochs: 10
  batch_size: 256
  lr: 0.0001
