default: &DEFAULT
  num_epochs: 1000
  batch_size: 256
  audio_processed_path: "data.json"

preprocess:
  <<: *DEFAULT
  audio_dir: "Data/genres_original"
  image_dir: "Data/images_original"
  sample_rate: 22050
  n_fft: 2048
  n_mfcc: 13
  hop_length: 512
  track_duration: 30
  num_segments: 10
  ignored_audio: "Data/genres_original/jazz/jazz.00054.wav"


MLP:
  <<: *DEFAULT
  model_name: MLP
  checkpoint_path: "checkpoints/mlp.pth"
  log_path: 'logs/mlp.json'
  num_epochs: 500
  batch_size: 32
  lr: 0.0001
  patience: 20

CNN:
  <<: *DEFAULT
  model_name: CNN
  checkpoint_path: "checkpoints/cnn.pth"
  log_path: 'logs/cnn.json'
  num_epochs: 100
  batch_size: 32
  lr: 0.0001
  patience: 10

LSTM:
  <<: *DEFAULT
  model_name: LSTM
  checkpoint_path: "checkpoints/lstm.pth"
  log_path: 'logs/lstm.json'
  num_epochs: 500
  batch_size: 32
  lr: 0.0001
  patience: 20
  hidden_size: 64


GRU:
  <<: *DEFAULT
  model_name: GRU
  checkpoint_path: "checkpoints/gru.pth"
  log_path: 'logs/gru.json'
  num_epochs: 500
  batch_size: 32
  lr: 0.0001
  patience: 10
  hidden_size: 64
